name: Maven Dependency Tree Dependency Submission
description: A GitHub Action for Maven project to submit a complete dependency tree to populate the GitHub Dependency Graph

branding:
  icon: alert-triangle
  color: red

inputs:
  directory:
    description: The directory that contains the maven project
    type: string
    default: ${{ github.workspace }}

  settings-file:
    description: Optional path to a Maven settings.xml file for the dependencies to be resolved
    type: string

  ignore-maven-wrapper:
    description: Flag for optionally ignoring any maven wrapper files (mvnw) and instead rely on the PATH provided mvn
    type: boolean
    default: false

  maven-args:
    description: Additional maven arguments to add to the command line invocation of maven when it generates the dependency snapshot
    type: string
    default: ''

  snapshot-include-file-name:
    description: Optionally include the file name in the dependency snapshot report to GitHub. This is required to be true if you want the results in the dependency tree to have a working link.
    type: boolean
    default: true

  snapshot-dependency-file-name:
    description: An optional override to specify the path to the file in the repository that the snapshot should be associated with.
    type: string
    required: false

  token:
    description: The GitHub token to use to submit the depedency snapshot to the repository
    type: string
    default: ${{ github.token }}

  ref:
    description: The ref to use when submitting the dependency snapshot to the repository, leave blank to use the current ref
    type: string
    required: false

  sha:
    description: The sha to use when submitting the dependency snapshot to the repository, leave blank to use the current sha
    type: string
    required: false

runs:
  using: node16
  main: dist/index.js
